language: C++

branches:
  only:
  - master

sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcfitsio3-dev
  
install:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make install
