# System Set-Up
language: cpp
compiler: gcc

# GitHub branch
branches:
  only:
  - master

sudo: false

# install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcfitsio3-dev

# set up installation
install:
  - mkdir build
  - cd build
  - cmake ..

# build package and install
script:
  - make install
  - make test

# notification settings
notification:
  email: false
