# System Set-Up
dist: trusty
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

# GitHub branch
branches:
  only:
  - master

sudo: false

# install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcfitsio3-dev

# set up installation
install:
  - mkdir build
  - cd build
  - cmake ..

# build package and install
script:
  - make install
  - make test

# notification settings
notification:
  email: false
