# System Set-Up
language: cpp

# install dependencies
addons:
  apt:
    packages:
      - cmake
      - libcfitsio3-dev
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - cfitsio

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        homebrew:
          packages:
            - gcc@7
            - *macos_packages
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
      addons:
        homebrew:
          packages:
            - llvm
            - libomp
            - *macos_packages

before_install:
  - eval "${MATRIX_EVAL}"

# set up installation
install:
  - mkdir build
  - cd build
  - cmake ..

# build package and install
script:
  - make install
  - make test

# notification settings
notification:
  email: false
