# System Set-Up
language: cpp

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# install dependencies
addons:
  apt:
    packages:
      - cmake
      - libcfitsio3-dev
  homebrew:
    packages:
      - gcc@7
      - cmake
      - pkgconfig
      - cfitsio

before_install:
  - eval "${MATRIX_EVAL}"

# set up installation
install:
  - mkdir build
  - cd build
  - cmake ..

# build package and install
script:
  - make install
  - make test

# notification settings
notification:
  email: false
