# System Set-Up
language: cpp

# install dependencies
addons:
  apt:
    packages:
      - cmake
      - libcfitsio3-dev
  homebrew:
    packages: &macos_packages
      - cmake
      - pkgconfig
      - cfitsio
    update: true

matrix:
  include:
    - os: linux
    - os: osx
      name: "macOS with GCC"
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      addons:
        homebrew:
          packages:
            - gcc
            - *macos_packages
    - os: osx
      name: "macOS with AppleClang"
      osx_image: xcode11.3
      addons:
        homebrew:
          packages:
            - libomp
            - *macos_packages

before_install:
  - eval "${MATRIX_EVAL}"

# set up installation
install:
  - mkdir build
  - cd build
  - cmake .. -DRUN_TESTS=OFF

# build package and install
script:
  - make install
  # - make test

# notification settings
notification:
  email: false
