language: cpp
compiler: gcc
dist: trusty

# GitHub branch
branches:
  only:
  - master

sudo: false

# install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcfitsio3-dev
  - sudo apt-get install -qq g++-7

# set up installation
install:
  - mkdir build
  - cd build
  - cmake ..

# build package and install
script:
  - make install
  - make test

# notification settings
notification:
  email: false
