name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Basic Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac cfitsio fftw libomp

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcfitsio-dev
          sudo apt-get install -y libfftw3-dev

      - name: Compile Sparse2D Binaries
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_FFTW=ON -DBUILD_MSVST=ON
          make

      - name: Run Unit Tests
        run: |
          cd build
          make test

      - name: Archive Unit Test Log
        uses: actions/upload-artifact@v2
        with:
          name: test-log
          retention-days: 14
          path: |
            build/Testing/Temporary/LastTest.log
