name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Basic Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac
          brew install cfitsio fftw libomp armadillo gsl healpix pybind11 python

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcfitsio-dev
          sudo apt-get install -y libfftw3-dev
          sudo apt-get install -y libarmadillo-dev
          sudo apt-get install -y libgsl-dev
          sudo apt-get install -y libsharp-dev
          sudo apt-get install -y libhealpix-cxx-dev
          sudo apt-get install -y healpy-data
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip
          python3 -m pip install pybind11
          pip show pybind11

      - name: Compile Sparse2D Binaries
        run: |
          mkdir build
          cd build
          cmake .. --log-level=VERBOSE
          make

      - name: Run Unit Tests
        run: |
          cd build
          make test

      - name: Archive Unit Test Log
        uses: actions/upload-artifact@v2
        with:
          name: test-log-${{ matrix.os }}
          retention-days: 14
          path: |
            build/Testing/Temporary/LastTest.log
